import { WINDOWS } from "nativewind/dist/utils/selector";
import { StyleSheet } from "react-native";
import {Dimensions} from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const myBlue = '#0672F7';
const myWidth = '86%'; 
const myGray ='#E5EBF2';
const myBoldGray = '#9EA1A5';
const myMaxLength = 40;
const mySpecBlue = '#19253D';

export const styles = StyleSheet.create({
    allWrapper: {
        flex: 1,
        backgroundColor: '#fff',
    },
    headerBar: {
        backgroundColor: '#77C9A3',
        width: '100%',
        height: 0.18 * windowHeight,
        borderBottomLeftRadius: 27,
        borderBottomRightRadius: 27,
    },
    headerImg: {
        position: 'absolute',
        right: 0.04 * windowWidth,
    },
    headerWrapper: {
        // borderWidth: 1,
        width: "80%",
        height: 0.06 * windowHeight,
        marginTop: 0.084 * windowHeight,
        marginLeft: 0.07 * windowWidth,
        flexDirection: 'row',
    },
    headerBtn: {
        backgroundColor: '#B9EAC4',
        height: '100%',
        aspectRatio: 1,
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTextWrapper: {
        marginLeft: 0.05 * windowWidth,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerText: {
        color: mySpecBlue,
        fontWeight: '500',
        fontSize: 0.016 * windowHeight + 0.016 * windowWidth,
    },
    searchWrapper: {
        marginTop: 0.04 * windowHeight,
        backgroundColor: '#F3F5F3',
        width: '86%',
        height: 0.06 * windowHeight,
        marginLeft: 0.07 * windowWidth,
        borderRadius: 100,
        // justifyContent:'center',
        flexDirection: 'row',
    },
    searchBtn: {
        // borderWidth: 1,
        marginLeft: 0.01 * windowWidth,
        height: "100%",
        aspectRatio: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchInputWrapper: {
        // borderWidth: 1,
        height: '100%',
        width: 0.67 * windowWidth,
        marginLeft: 0.00 * windowWidth,
        fontSize: 0.015 * windowHeight + 0.015 * windowWidth,
    },
    dateWrapper: {
        height: 0.11 * windowHeight,
        width: '86%',
        marginTop: 0.016 * windowHeight,
        marginBottom: 0.018 * windowHeight,
        marginLeft: 0.07 * windowWidth,
        borderWidth: 1,
        borderRadius: 18,
        borderColor: myGray,
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-evenly',
    },
    avtDateWrapper: {
        marginTop: 0.008  * windowHeight,
        height: 0.078 * windowHeight,
        aspectRatio: 1,
        // borderWidth: 1,
        borderRadius: 12,
    },
    avtDate: {
        height: '100%',
        width: '100%',
        resizeMode: 'cover',
        borderRadius: 12,
    },
    labelDateWrapper: {
        marginTop: 0.004 * windowHeight,
        height: 0.08 * windowHeight,
        width: 0.57 * windowWidth,
        marginRight: 0.04 * windowWidth,
        // borderWidth: 1,
    },
    textDateWrapper: {
        width: '100%',
        height: '60%',
        // borderWidth: 1,
        marginBottom: 0.009 * windowHeight,
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    textDate: {
        fontSize: 0.0108 * windowHeight + 0.0108 * windowWidth,
        fontWeight: '500',
        color: '#000',
    },
    nameDate: {
        fontSize: 0.0112 * windowHeight + 0.0112 * windowWidth,
        color: '#77C9A3',
        fontWeight: '500',
    },
    btnDateWrapper: {
        width: '56%',
        height: '44%',
        // borderWidth: 1,
        borderRadius: 11,
        backgroundColor: '#77C9A3',
        alignItems: 'center',
        justifyContent: 'center',
    },
    textBtn: {
        color: '#fff',
        fontSize: 0.011 * windowHeight + 0.011 * windowWidth,
    },
    chatListLabel: {
        marginTop: 0.016 * windowHeight,
        marginLeft: 0.07 * windowWidth,
    },
    chatListTextLabel: {
        fontSize: 0.018 * windowHeight + 0.018 * windowWidth,
        color: mySpecBlue,
        fontWeight: '500',
    },
    chatListWrapper: {
        // flex: 1,
        marginTop: 0.016 * windowHeight,
        marginBottom: 0.05 * windowHeight,
        width: '100%',
    },
    chatItemWrapper: {
        width: '86%',
        marginLeft: 0.07 * windowWidth,
        height: 0.09 * windowHeight,
        marginBottom: 0.014 * windowHeight,
        borderRadius: 16,
        backgroundColor: '#F3F5F3',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-evenly',
    },
    chatAvtWrapper: {
        // borderWidth: 1,
        height: '74%',
        aspectRatio: 1,
        borderRadius: 100,
    },
    chatAvt: {
        borderRadius: 100,
        height: '100%',
        width: '100%',
        resizeMode: 'cover',
    },
    chatDesWrapper: {
        height: '74%',
        width: 0.62* windowWidth,
        // borderWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    chatDesLeftWrapper: {
        height: '100%',
        width: '85%',
        // borderWidth: 1,
        flexDirection: 'column',
    },
    chatNameWrapper: {
        height: '60%',
        width: '90%',
        // borderWidth: 1,
    },
    chatNameText: {
        color: mySpecBlue,
        fontSize: 0.015 * windowHeight + 0.015 * windowWidth,
        fontWeight: '500',
    },
    chatMessWrapper: {
        height: '40%',
        width: '100%',
        // borderWidth: 1,
    },
    chatMessText: {
        fontSize: 0.011 * windowHeight + 0.011 * windowWidth,
        color: myBoldGray,
    },
    chatDesRightWrapper: {
        height: '100%',
        width: '12%',
        // borderWidth: 1,
        flexDirection: 'column',
        alignItems: 'center',
    },
    chatTimeWrapper: {
        height: '40%',
        width: '100%',
        // borderWidth: 1,
        // marginTop: 0.004 * windowHeight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    chatTimeText: {
        color: myBoldGray,
        fontSize: 0.0104 * windowHeight + 0.0104 * windowWidth,
    },
    chatNewMessWrapper: {
        marginTop: 0.003 * windowHeight,
        borderRadius: 100,
        // borderWidth: 1,
        width: '68%',
        aspectRatio: 1,
        backgroundColor: '#EE583C',
        justifyContent: 'center',
        alignItems: 'center',
    },
    chatNewMessText: {
        color: '#fff',
        fontSize: 0.009 * windowWidth + 0.009 * windowHeight,
        fontWeight: '500',
    },
    headerChatBar: {
        backgroundColor: '#77C9A3',
        width: '100%',
        height: 0.18 * windowHeight,
        borderBottomLeftRadius: 27,
        borderBottomRightRadius: 27,

        shadowColor: '#000',
        elevation: 0.02 * windowHeight,
    },
    headerInfoWrapper: {
        marginLeft: 0.05 * windowWidth,
        alignItems: 'center',
        justifyContent: 'center',
        // borderWidth: 1, 
        height: '100%',
        width: 0.64 * windowWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    headerAvtWrapper: {
        height: '100%',
        aspectRatio: 1,
        borderRadius: 100,
        // borderWidth: 1,
    },
    headerAvt: {
        height: '100%',
        width: '100%',
        borderRadius: 100,
        resizeMode: 'cover',
    },
    headerStatusWrapper: {
        backgroundColor: '#fff',
        position: 'absolute',
        height: 0.016 * windowHeight,
        aspectRatio: 1,
        bottom: 0,
        right: 0.008 * windowWidth,
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerStatus: {
        backgroundColor: '#86EE9B',
        height: '74%',
        aspectRatio: 1,
        borderRadius: 100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerDesWrapper: {
        height: '100%',
        width: '74%',
        // borderWidth: 1,
        marginLeft: 0.026 * windowWidth,
        flexDirection: 'column',
    },
    headerNameWrapper: {
        width: '100%',
        height: '60%',
        // borderWidth: 1,
        // marginBottom: 0.003 * windowHeight,
    },
    headerNameText: {
        color: mySpecBlue,
        fontSize: 0.016 * windowHeight + 0.016 * windowWidth,
        fontWeight: '500',
    },
    headerTimeWrapper: {
        marginTop: -0.006 * windowHeight,
        width: '100%',
        height: '35%',
        // borderWidth: 1,
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    headerTimeText: {
        color: '#fff',
        fontSize: 0.01 * windowHeight + 0.01 * windowWidth,
    },
    chatAllWrapper: {
        marginTop: 0.012 * windowHeight,
        flex: 1,
        // backgroundColor: '#F3F5F3',
        flexDirection: 'column',
        justifyContent: 'flex-end',
    },
    chatBoxWrapper: {
        width: '100%',
        height: 0.1 * windowHeight,
        // borderWidth: 1,
        backgroundColor: '#fff',
    },
    chatTypingWrapper: {
        width: '100%',
        height: 0.05 * windowHeight,
        // borderWidth: 1,  
        backgroundColor: '#fff',
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
        flexDirection: 'row',
    },
    chatTypingAvtWrapper: {
        height: '80%',
        aspectRatio: 1,
        // borderWidth: 1,
        borderRadius: 100,
        marginLeft: 0.02 * windowWidth,
        marginBottom: 0.004 * windowWidth,
    },
    chatTypingAvt: {
        height: '100%',
        width: '100%',
        resizeMode: 'cover',
        borderRadius: 100,
    },
    chatTypingTextWrapper: {
        height: '100%',
        width: '80%',
        // borderWidth: 1,
        marginLeft: 0.03 * windowWidth,
        justifyContent: 'center',
    },
    chatTypingText: {
        color: myBoldGray,
        fontStyle: 'italic',
        fontSize: 0.011 * windowHeight + 0.011 * windowWidth,
    },
    chatInputWrapper: {
        width: '96%',
        height: '56%',
        marginTop: 0.012 * windowHeight,
        // borderWidth: 1,
        marginLeft: 0.02 * windowWidth,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    chatAddBtnWrapper: {
        height: '100%',
        aspectRatio: 1,
        borderRadius: 100,
        backgroundColor: '#2B7EFF',
        justifyContent: 'center',
        alignItems: 'center',
    },
    chatInputTextWrapper: {
        height: '100%',
        width: '84%',
        // borderWidth: 1,
        borderRadius: 100,
        backgroundColor: '#E9ECEA',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    chatInputText: {
        height: '100%',
        width: '78%',
        // borderWidth: 1,
        marginLeft: 0.024 * windowWidth,
    },
    chatEmojiWrapper: {
        height: '100%',
        aspectRatio: 1,
        // borderWidth: 1,
        marginRight: 0.024 * windowWidth,
        justifyContent: 'center',
        alignItems: 'center',
    },
    chatMessListWrapper: {
        flex: 1,
        width: '100%',
        // backgroundColor: 'red',
        marginBottom: 0.012 * windowHeight,
    },

    itemWrapper: {
        backgroundColor: '#fff',
        paddingHorizontal: 0.03 * windowWidth,
        marginHorizontal: 0.07 * windowWidth,
        paddingVertical: 0.01 * windowHeight,
        marginVertical: 0.01 * windowHeight,
        alignSelf: 'flex-start',
        maxWidth: 0.72 * windowWidth,
        borderRadius: 8,
    },
    itemRight: {
        alignSelf: 'flex-end',
        backgroundColor: mySpecBlue,
    },
    itemTextLeft: {
        color: mySpecBlue,
        fontSize: 0.012 * windowHeight + 0.012 * windowWidth,
    },
    itemTextRight: {
        color: '#fff',
        fontSize: 0.012 * windowHeight + 0.012 * windowWidth,
    },

    allChatWrapper: {
        backgroundColor: '#EDF2EE',
    }
})